<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>business_rule</name>
  <uuid>666265d9-435a-4a39-8586-5eb83b24d2ee</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if
	Input 
then
	set decision to "working" ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
